name: python-runtime-core24-312
base: core24
adopt-info: python
summary: Runtime snap for Python 3.12 on core24.
description: |
  ...

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

slots:
  python-runtime:
    content: python-runtime-core24-312
    interface: content
    read:
    - "."

parts:
  python:
    plugin: nil
    build-packages:
      - jq
      - zstd
    stage-packages:
      - base-files_chisel  # Generate manifest
      - python3_standard
      - python3.12-venv_ensurepip  # Allow creating the virtual environment.
    build-attributes:
      - enable-patchelf
    override-build: |
      craftctl default
      craftctl set "version=$(cat "${CRAFT_PART_INSTALL}/var/lib/chisel/manifest.wall" | unzstd | jq -r '. | select(.name=="python3.12") | .version')"

      # Delete all files in the install dir that already exist in the base snap.
      pushd /snap/core24/current
      find . -type f | grep -v python > /tmp/core24_files.list
      popd
      pushd "${CRAFT_PART_INSTALL}"
      find . -type f | grep --file=- /tmp/core24_files.list -F | xargs rm
      popd

      # Delete broken links
      find "${CRAFT_PART_INSTALL}" -xtype l -delete

