name: Test
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - hotfix/*

jobs:
  snap-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ^1.23.0
      - name: Install spread
        run: |
          go install github.com/snapcore/spread/cmd/spread@latest

      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Install LXD
        uses: canonical/setup-lxd@v0.1.3

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: true

      - name: Prepare snaps
        run: |
          ./prepare-tests.sh

      - name: Run spread
        run: |
          spread

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
